### PR TITLE
[ENG-4072]  fixes typo of i4 instance type that caused a rollbar

### PR DESCRIPTION
**Pull request by amose679**
fixing typo

Rollbar: #45172 CloudHealth::RightsizingJobError: Computing aws:ec2:instance scores for asset_id 2542620950959 failed: undefined method `index' for nil:NilClass

### CODE REVIEW

**Comment by emjaymikes** [comment]
Guessing you need to update `lib/amazon-pricing/version.rb` too, but Stan would know better.

**Comment by stanmluke** [comment]
@emjaymikes is correct, we need to bump version.rb (since this is a public gem).

deploying this change is two parts:

1. committing this change, publishing the updated a-p gem.
2. once published, we need to update all artifacts which use the a-p gem to pull in this new version (hence why we need a version bump);  this probably includes all deploys.

**Comment by amose679** [comment]
Thanks for the catch! Is there documentation on how to do part 2?

**Comment by stanmluke** [comment]
you need perms to publish, so I believe Joe or Jeff need to give perms.  (Jeff gave them to me.)

otoh, I can publish for you when you're ready (i.e. right before you deploy).  Technically you should update the deploy Gemfile to match this version, which would stop an accidental regression by pulling in an older version.

**Pull request merged**
